### ISSUE TITLE
PowerBI Desktop Option Greyed Out

### ISSUE THREAD

**Issue by jsaulez** [microsoft/Analysis-Services#121]
Hi. When i launch ALM from PBI Desktop, the source option to choose the PBIX file that is open is greyed out. I cant choose it as a source.

**Comment by nphadro07** [comment]
I am experiencing the same issue. is there a resolution?

**Comment by christianwade** [comment]
Hi all, that option is only enabled when Power BI Desktop is open in the background, normally when launch as an external tool as described here: http://aka.ms/externaltools

**Comment by nphadro07** [comment]
@christianwade Thanks so much for the reply. I am launching it through the external tool ribbon in Power BI. As you suggest, I thought this option would be enabled similar to how when I launch dax studio it connects to the desktop model. Any thoughts?

**Comment by christianwade** [comment]
No worries. I'm not sure what's causing this. I'd love to find out but I suspect it is environment specific. I just tried with the latest ALM Toolkit version and I'm not getting that behavior. It's difficult to debug when I can't reproduce the problem on my development environment.

It's definitely interesting that DAX Studio connects since it should be doing the same thing. 

As a workaround in the meantime, you can connect with DAX Studio and get the local server name with the port number like (for example localhost:61432) from the status bar in DAX Studio. Then paste it into the source Workspace field and click the dropdown to get the dataset name.

![image](https://user-images.githubusercontent.com/20731873/181116471-11942481-9b82-4bd5-b850-dcc07750c38c.png)

![image](https://user-images.githubusercontent.com/20731873/181116553-83d990ae-66c4-4672-beed-47bd12fe702c.png)

**Comment by nphadro07** [comment]
@christianwade I agree that it seems strange that it is not working. But your work around works perfect. Thank you for your quick response.

**Comment by nheuk** [comment]
Same problem here with Power BI Desktop September and ALM 5.0.33
Workaround works with Dax Studio or Tabular Editor

**Comment by christianwade** [comment]
I'll keep an eye out for an opportunity to repro it on my dev environment
