### ISSUE TITLE
Can ALM toolkit store Data,during the comparision of Metadata

### ISSUE THREAD

**Issue by 02Sush** [microsoft/Analysis-Services#124]
there is a check box in the options:
for Table updates, retain storage mode
Can it enable storage option in the tool to store the Data associated with the metadata which is used for comparison?

Can we use ALM toolkit with XMLA settings in READ ONLY status, to query and compare the Datasets in Workspace?

**Comment by christianwade** [comment]
Hi, the AS engine automatically retains whatever data it can based on the metadata change. For example, adding a column to an import table/partition query retains the existing data, but has blanks for the new column. Deleting a partition metadata deletes its data too. So as long as you don't change any metadata that would cause data loss, it should work.

Yes, you can use ALM Toolkit for comparison only if the capacity is read only since it won't be making any write updates.
