### ISSUE TITLE
ALM Toolkit: 5.0.28

### ISSUE THREAD

**Issue by JulianPayne-Align1st** [microsoft/Analysis-Services#152]
ALM Toolkit freezes when we try to "Update". App freezes upon update action.

We are using an Azure VM. I can provide more details if needs be, but stability on our VM seems to be an issue. 

Has anyone else reported the app not responding upon attemepts to update?

**Comment by christianwade** [comment]
Hi Julian, the most common cause of this type of experience is the TOM transaction is taking a long time. There can be various reasons for this like ongoing queries or other reasons. Generally, if you wait, it will go through. If you want to confirm this is the cause and the issue is repeatable, you can - instead of committing the update by clicking the Update button - script it out to a TMSL script using the Script button - and run the script from SSMS. This is basically the same as what ALM Toolkit is doing, but it may provide a bit more diagnosis info by running from SSMS.

**Comment by christianwade** [comment]
You're welcome!
