### ISSUE TITLE
Website insecure

### ISSUE THREAD

**Issue by rhartopAW** [microsoft/Analysis-Services#241]
![image](https://github.com/microsoft/Analysis-Services/assets/57706719/edd972c7-c05c-4b58-93b4-df5ccd861245)

This is stopping us from downloading and using the ALM toolkit

**Comment by christianwade** [comment]
Hi, sorry to hear this is blocking you. This website was created a long time ago (it's a derivation of https://bism-normalizer.com/) and hasn't been updated for many years.

ALM Toolkit is an open source community tool with a limited number of contributors. Unfortunately there is no plan to update this website because there is a backlog of high priority enhancements that need to get done like TMDL based diffs and digital certs for the installation files.

Can you refer to GitHub releases instead? https://github.com/microsoft/Analysis-Services/releases

**Comment by rhartopAW** [comment]
Hi Christian, thank you for the update. Using the GitHub release worked well, many thanks.

**Comment by christianwade** [comment]
Good to hear!
