### ISSUE TITLE
BISM Normalizer Compatibility Issue

### ISSUE THREAD

**Issue by eddingtonm** [microsoft/Analysis-Services#27]
Hi All,

I have two models with a compatibility level of 1465. I cannot merge changes from one model to the other due to the Normalizer's version.

The specific error that returns is:

![bism normalizer](https://user-images.githubusercontent.com/11536776/51894888-a0795300-23b1-11e9-855b-9b06c81a4d22.PNG)

There is no purchase page on the BISM Normalizer website.

Any ideas on how I could get this compatibility level to work on the version that is out there...Which is **4.0.0.30**?

Thanks

Eddie

**Comment by christianwade** [comment]
Hi, that's a very old version :). The new version wouldn't direct you to that web page.

Even with the latest version it wouldn't support 1465 though because that compat level isn't supported by SSDT in VS.

If you want to perform a comparison on 2 models not in VS using that version, please try http://www.alm-toolkit.com/. It's the same codebase as BISM Normalizer, but doesn't run in VS and supports compat level 1465
