### ISSUE TITLE
No room is available to display rows

### ISSUE THREAD

**Issue by gowheya** [microsoft/Analysis-Services#44]
Hi  there , just encounter this strange error while comparing target with source in Tabular model using BISM normaliser. Do any one knows the reasons why this pops up?

**Comment by gowheya** [comment]
![Capture](https://user-images.githubusercontent.com/27489336/74853046-47ba8680-5335-11ea-9a9e-5241e8d7aa81.PNG)

**Comment by christianwade** [comment]
I've been trying to reproduce this one on my development environment for a long time! It has been reported by a handful of people. They have sent me the project and BISM files and I was still unable to reproduce it. I even went as far as installing the whole development environment on one of their machines and when I ran it in debug mode, it didn't repro :(.

To unblock you, perhaps try one of the following options?

- See if there is a VS update or something you can apply. Others told me that it went away for some reason.
- Use the ALM Toolkit instead as a workaround (till hopefully this goes away as it has for others). You should be able to download the installer from here. If you use ALM Toolkit, you can connect to your local SSDT AS instance by selecting it in the "Power BI Desktop" dropdown in the Connections dialog.

**Comment by dmayi** [comment]
I faced this situation just a couple of days ago. The BISM Normalizer  extension v5.0.4.2 was working fine on my SSDT 2017 15.9.23 installation, then suddenly it started happening. I tried various things, including removing the latest tables i added tot he model, unistalling/reinstalling the extension. 

Solution:  I uninstalled and re-installed SSDT 2017 15.9.23. The issue was cleared.
