### ISSUE TITLE
Creating Objects from Source to Target results in "unknown" Data Type

### ISSUE THREAD

**Issue by mtthsbrr** [microsoft/Analysis-Services#49]
Hi,

here is what I did:
- use v5.0.3 on Win 10
- loaded .pbit as source
- loaded .bim as target
- created objects from source to target

After creating all objects the tool still indicates a lot of "update". When checking in detail, I see dataType in target not being set as in source but to "unknown" instead. A second run of "Validation" and "Update" is not solving it.

Screen:
![image](https://user-images.githubusercontent.com/49281986/79642322-1fb49b80-819d-11ea-88f5-46c67569676a.png)

**Comment by christianwade** [comment]
Hi, can you republish the PBI Desktop dataset with enhanced dataset metadata preview feature set to true?

**Comment by mtthsbrr** [comment]
Hi, sorry - but we are not on premium so we can only use local files. As it seems, there is no way to create a .pbit from a .bim file anyway but that was my hope somehow. Hopefully .pbit files support creating objects anytime soon to get us there.

![image](https://user-images.githubusercontent.com/49281986/79924506-3591bd00-8438-11ea-8efe-38c4f7ac2e09.png)

This can be closed IMHO. Thanks

**Comment by christianwade** [comment]
Yeah, Desktop needs to be hardened to external tool changes before that will work.

I see the problem now. It's because calculated columns have dynamic data types based on the data types of the data referred to by the column definition. When loading from a BIM file or JSON definition, those data types are not retained.

Do you need all those date tables? They are auto generated by Desktop if you have Options > Data Load > Auto date/time enabled. If you uncheck it, they will be removed.

Date tables aside, for the occasional calc column, can you ignore the warning? Not sure what else to do since the data type can't be implied.
