### ISSUE TITLE
Failed to save modifications to the server

### ISSUE THREAD

**Issue by Felipe8345** [microsoft/Analysis-Services#50]
Hello Christian,

I've been testing ALM toolkit and it seems to be corrupting the power bi file. 

1. Created a model in power bi. Used parameters to select a data range. Defined incremental policy. 
2. Published to Service, premium workspace. 
3. Connected to Premium workspace and compared dataset with the power bi file ("Power BI Desktop" option), as per picture below.

![ALM connection](https://user-images.githubusercontent.com/63748003/80073410-08cccb00-8548-11ea-9e67-1acf2e3cea75.png)

4. Added a measure in desktop and deployed new components to the dataset in Power BI Service.

Then I carried on with my testing and wanted to add a new table (on the power bi file), but after I clicked "Close and Apply" in Power Query I got the following error:

![Load error](https://user-images.githubusercontent.com/63748003/80073736-7b3dab00-8548-11ea-8326-8b7bc3cc3724.png)

I've seen some people coming across the same issue:
https://community.powerbi.com/t5/Desktop/Failed-to-save-modifications-to-the-server-when-calling-API/td-p/990136

The issue is solved if I remove the incremental policy in desktop. 

Is this a known issue?

Btw, thank you so much for doing this wonderful tool, it is going to be a game changer for enterprise deployments. :)

Felipe,

**Comment by christianwade** [comment]
Hi Felipe, 

Currently there are numerous blocks on making changes to a PBIX that is set as the target of a comparison because Desktop is not hardened to external model changes yet. It does however allow changes to measures although you should wait for the official Desktop build that launches 3rd party tool integration before doing this. I was hoping this would be ready by the time I made ALM Toolkit available. If necessary, I can block these changes to a PBIX till it's ready.

If you want access to the private preview of Desktop that will allow this (with the external tools ribbon), please let me know. Assuming your company has an NDA with Microsoft, I can add you to the private preview Teams channel which is where it will be launched in a few weeks.

Christian

**Comment by jiteshparwal93** [comment]
Hi Christian,

I was just checking this issue as I am facing another.
I will like to be added in Private Preview of Desktop version, as my org have NDA with Microsoft.
If you need my id let me know.

**Comment by christianwade** [comment]
Can you please fill in [this survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRwtYMmEoxmBAmEkLDcoMX4xUN1NTN1Q0RjFIRlRENENGUUxWSVRRTUw2Ui4u) so I can add you to the teams channel?

**Comment by Felipe8345** [comment]
Thank you Christian.
I have filled out the survey.
I would love to try the the preview.
Just to clarify, my target was not a desktop file but a dataset in Service. 
I've seen your videos and I'm fully aware the current limitation in desktop.

Best regards,
