### ISSUE TITLE
ALM Toolkit does not flag different themes when comparing models

### ISSUE THREAD

**Issue by dbszepesi** [microsoft/Analysis-Services#69]
I did not see a way to turn this on but if it is exposed through the API, it would be very valuable to be able to see if themes in use are different between two PBIX files.  For instance, I have a PBIX where someone went in and applied a theme.  When I compare that PBIX to my copy of it (without the custom theme applied), ALM does not flag a difference or give me the ability to generate a script to synch the two.

This would be pretty helpful to have in scenarios where a front-end type developer is making theme changes on a shared PBIX.

**Comment by christianwade** [comment]
Thanks for the feedback. We agree that standardized metadata will be valuable for a bunch of other artifacts (interactive reports, data flows, dashboards, etc.). We want to get there, but it's a lot of work, so currently focusing on dataset metadata and hardening to external model changes since we have a head start in that area given our history with Analysis Services.

**Comment by dbszepesi** [comment]
Makes sense, thanks for the follow up!
