### ISSUE TITLE
ALM Tookit is not applying the updates

### ISSUE THREAD

**Issue by jkapoio** [microsoft/Analysis-Services#80]
ALM Tookit is not applying the updates. After clicking "Update" and making a new comparison, it appears that the update was not applied. Attached, the files model.bim soure and target.

ALM Toolkit Version: 5.0.12

Model.bim (Source) -> .. \ AMPM \ Model (Source) .bim
Model.bim (Target) -> ... ModelReview \ Model (Target) - before merge
[AMPM x ModelReview.zip](https://github.com/microsoft/Analysis-Services/files/5532249/AMPM.x.ModelReview.zip)

**Comment by christianwade** [comment]
Hi, can you please try it with "For table updates, retain partitions" unchecked?

![image](https://user-images.githubusercontent.com/20731873/99019649-a18d5d00-2511-11eb-8f58-93259ca141eb.png)

**Comment by jkapoio** [comment]
Hi, Crhis.

If I have partitions created and loaded into Target (Analysis Services Server), wouldn't that option delete partitions and data? I need to keep the partitions that have already been created and loaded.

**Comment by christianwade** [comment]
Hi,
Is the question why are these tables still listed as different (with "Different Definitions" and "Update" action item even though the merge has been applied?

Technically it does perform the update, but it keeps the partition definitions in the target tables because of the "For partition objects, retain definitions" setting. When the comparison is run again, they come up as different because it simply compares the string text definition of objects to determine if they have "Different Definitions". If the problem is that they keep coming up as different, I wouldn't worry about that and just ignore it. Does that make sense/help?

![image](https://user-images.githubusercontent.com/20731873/99137531-3ced0380-25e0-11eb-8bcb-79387eb46a85.png)

**Comment by jkapoio** [comment]
Thank you Crhis for the explanation.

I made a new Deploy to update 2 tables (and 1 perspective), but it didn't update in Target. The tables are Dimension tables: DM_CRITERIO and DM_TIPO_NEGOCIO. Tables have only one partition (the default partition). After updating the target and answering "Yes" the message "Do you want to refresh the comparison",
the same tables (and perspective) appeared as "different definitions". I checked the target and noticed
that hasn't really been updated.

ALM Toolkiet Version: 5.0.12

Attached are the files model.bim, source and target.

**Comment by christianwade** [comment]
Hi, did you uncheck "For partition objects, retain definitions"?

**Comment by jkapoio** [comment]
I hadn't cleared it. After I uncheck, it updated. As it is a dimension, it only has one partition (default),
OK,  but when I have several partitions in Target, if I uncheck this option, it will not delete the partitions
that already exist on Target?

**Comment by christianwade** [comment]
Yes, that is correct. If using AAS/SSAS and creating the partitions yourself (instead of incremental refresh in Power BI where can limit to just refresh-policy based partitions), then there is no option to retain partitions for 1 table but not another. You would have to apply 2 different comparisons with the setting on/off and skip the tables that do/do not need to retain partitions.

**Comment by jkapoio** [comment]
ok, I got it. I think I will have to divide Deploy into 2 parts, then: First for Dimensions and
the second for Facts (these are partitioned by an external process). I think so, it should
work.

**Comment by christianwade** [comment]
Yes, that will work. I never got round to prioritizing the ability to choose retain partitions at the table level, partly because this problem goes away with incremental refresh polices. Glad you have a workaround anyway.

**Comment by jkapoio** [comment]
Chris, thank you very much. thanks for the explanations, your patience and your time (and the ALM Toolkit, of course). 
Thank you so much.

**Comment by christianwade** [comment]
You're welcome!
