### ISSUE TITLE
BISM Normalizer extremely slow displaying differences for a table with many partitions

### ISSUE THREAD

**Issue by EylesIT** [microsoft/Analysis-Services#82]
I have a tabular model cube which has over 1000 partitions. 
In the tabular model project, the table has around 20 partitions.
The text length of the partitions is around 9000 characters.
The number of partitions differ between the project file and the cube in production because in the tabular model project, we only define a set of template partitions, while in the cube we have the template partitions plus partitions for each day and month which are populated and processed using a separate tool.
When doing a Compare, which only takes around 1 minute, the table appears showing Status "Different Definitions". The compare is done between the tabular model project against the SSAS database.
But if I click on the row itself, the Windows hourglass appears and Visual Studio is "busy" and unresponsive for around 30-60 minutes. It seems that BISM Normalizer is doing something strange when attempting to produce the Source Object Definition and Target Object Definition differences.

Is this a length of time expected, or does this indicate a bug/performance issue with BISM Normalizer?

The version is 5.0.12.1
The Compare options are:
![image](https://user-images.githubusercontent.com/60180107/100284794-a9182180-2f67-11eb-8684-17de9c551b94.png)

**Comment by christianwade** [comment]
Hi,

Yeah, the diff control in BISM Normalizer is the old one that is winforms based and can struggle with massive object definitions. The new one in ALM Toolkit should address this issue, but since it's typescript based and hosted in chromium, it's not hosted in VS.

Possible things to try:
- See if it works for you with "Consider partitions when comparing tables" unchecked. This will omit the JSON for the partitions and could considerably reduce the size and possibly make it manageable for the control. The implications of unchecking this are that the partitions will not be considered when determining if the table has "different definitions", but since you have a separate tool that manages partitions in the service anyway, you may not need the partition definitions. Note that if there are other differences in the table (e.g. column deletion or data type change) and it is determined to have "different definitions", and you then apply an "Update", it will replace the partitions as well **_unless_** you have "For table updates, retain partitions" (in which case the target partitions will be retained).
- If the above doesn't work for you, you could try ALM Toolkit. It can connect to SSDT and the SSDT project will be listed in the "Power BI Desktop" dropdown in the Connect dialog (even though it runs outside VS).

**Comment by EylesIT** [comment]
Thanks christianwade, that ALM Toolkit works a treat. It displayed the differences in the tables with 1100 partitions in just a few seconds.

**Comment by christianwade** [comment]
Great!
