### ISSUE TITLE
Unable to create table because target is power BI desktop or pbit which does not yet support modification of this type

### ISSUE THREAD

**Issue by Churchill59** [microsoft/Analysis-Services#89]
Hello,

I do not see any restriction or configuration in the How To. Is it impossible to update a Power BI desktop model?

I get the following error:
![image](https://user-images.githubusercontent.com/22095760/106259940-268a3780-6220-11eb-86f6-42cad91944a6.png)

Thank you

**Comment by christianwade** [comment]
Hi, there is work that needs to be done ("Desktop hardening") for Power BI Desktop to safely allow external model changes beyond what is documented here:
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations
This of course only applies if the dataset is the Desktop hosted one.

**Comment by BAAAASS** [comment]
@christianwade Your response does not make any sense.  The error above is received when using an already integrated external tool "ALM Toolkit".
The error (warning) occurs when you compare two models and the target is PowerBI.  It says that it cannot update PowerBI.  Please help me understand how the article you linked to helps or solves this issue?

**Comment by BAAAASS** [comment]
Hi

Yes, thank you.  I saw this after I sent the message (which I subsequently deleted).  The OP & the article specifically talk about Table Creation - instead, I am having issues with Relationships not updating, but measures are updating correctly.  My thought was that this is different, but since the article also doesn't specifically say that relationships are allowed updating, I assume that this is also not allowed.

All cleared up now, Thanks again!


Kind Regards,
BAAAASS
________________________________

**Comment by Kpham-RDMKR** [comment]
@christianwade  
Hi Christian,

I'm running into the same problem as @Churchill59. I cannot update tables or relationships in my desktop version. I have read your comment about "desktop hardening" and I can't really figure out how to finish the desktop hardening. I can see that the JSON file is in the correct folder:
`"C:\Program Files (x86)\Common Files\Microsoft Shared\Power BI Desktop\External Tools\almtoolkit.pbitool.json"`
Can I do something so that the I can sync with the Power BI desktop or is this impossible at this moment?

Thank you in advance

Khoi

**Comment by christianwade** [comment]
Hi all, sorry for delayed response. Power BI Desktop hardening is required to make this happen. It's being done, but not ready quite yet ...

**Comment by BadAtDax** [comment]
> Hi all, sorry for delayed response. Power BI Desktop hardening is required to make this happen. It's being done, but not ready quite yet ...

Is it ready now? :)

**Comment by christianwade** [comment]
Nope 🙂 Copying @RuiRomano  for viz
