### ISSUE TITLE
ALM Toolkit - Error Deploy

### ISSUE THREAD

**Issue by jkapoio** [microsoft/Analysis-Services#90]
When trying to do a simple deploy, I am making an error. Any deploy, from any database, I get an error message and depoloy is not performed. Can you help me ? 
[Erro Deploy AS.zip](https://github.com/microsoft/Analysis-Services/files/5921325/Erro.Deploy.AS.zip)

**Comment by christianwade** [comment]
Hi, this is a known bug in AAS. It is being investigated and hopefully will be fixed soon.

It is caused by related to special characters in object name references (e.g. Perspective table/column names that use certain special characters). You may be able to workaround this by deleting the DB, removing special characters like '.', '[', ']', ':', '$' and redeploying, but we’re still validating the details of the problem and will hopefully rollback the regression soon…

**Comment by jkapoio** [comment]
ok. Thank you, Chris.
