### ISSUE TITLE
ALMToolkit: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by dgwilson** [microsoft/Analysis-Services#98]
Source Model = Desktop - 64 Bit - February 2021 release. Also uses composite model.
Destination Model = Power BI Service

Click compare - screen does not show any data/info - only reports "Object reference not set to an instance of an object".

Source model = 203MB  - Uses Incremental Refresh and now composite model too.
Same pbix was published to service and successfully refreshed in the service.

I intend to retest by publishing model and connecting with ALM Toolkit prior to refresh. (i.e. after no change).

- David

**Comment by dgwilson** [comment]
Update on the retest.
PBIX Uploaded to workspace (that I'm the Admin of - workspace does contain other models).
Connection attempt with ALM toolkit - fails with Object reference not set to an instance of an object.

**Comment by christianwade** [comment]
Hi David, is the service Premium Gen1, Gen2, PPU or Pro?

**Comment by dgwilson** [comment]
Hi Christian. It's Premium (and as I'm not the premium Admin, I think it will be Gen1?)
I have just deleted the connection to the Composite model and republished. Success I'm able to complete the compare.
- went to Data Source settings, right click and delete. then Save and Publish and connect with ALM Tool Kit. Success.

**Comment by christianwade** [comment]
Thanks for the heads up. Will look into it ...

**Comment by Embedded82** [comment]
@christianwade I can confirm the same use case of @dgwilson 
Source Model = Version: 2.90.782.0 64-bit (February 2021)
Destination Model = Power BI Service - Premium Workspace Gen1
Model with incremental refresh and composite model (Using DirectQuery for Power BI datasets)

Connection attempt with ALM toolkit - fails with Object reference not set to an instance of an object.

Deleted the Power BI dataset data source I was connecting in DirectQuery and republished and connect with ALM Tool Kit with success.

**Comment by vbogullu** [comment]
Similar issue as above - on the first compare it did mention version differences between Source and Destination.
Do you think upgrading to Gen 2on the service will fix this? Thanks.

**Comment by christianwade** [comment]
Sorry for delayed response on this.

Are you still getting this issue? I seem unable to repro. If yes, I'd like to find a way to repro, but might be tricky if depends on the source model for the composite model.

The different versions message, if you mean detection of compatibility levels, this is by design.

**Comment by vbogullu** [comment]
Hi Christian,
ALM Toolkit still fails with “object reference not set to an instance of an object” when we are comparing power bi service composite model that has more than 1 power bi dataset.

For now we are comparing individual power bi datasets that make up the composite model. Let me know if you need any other information.

Thanks,
Vamsi.
On Apr 30, 2021, at 8:03 PM, Christian Wade ***@***.***> wrote:

﻿
[WARNING] EXTERNAL EMAIL: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Sorry for delayed response on this.

Are you still getting this issue? I seem unable to repro. If yes, I'd like to find a way to repro, but might be tricky if depends on the source model for the composite model.

The different versions message, if you mean detection of compatibility levels, this is by design.

**Comment by dgwilson** [comment]
@christianwade <https://github.com/christianwade> I've retested this and
the same error prevails.
 "Object reference not set to an instance of an object"

I've now upgraded ALM Toolkit to 5.0.19 - the same error message is still
emitted.

Next Step - upgrade Power BI Desktop version and republish
Source Model = Version: 2.92.706.0 64-bit (April 2021)
Destination Model = Power BI Service - Premium Workspace Gen2 (I think)

I've saved the PBIX desktop file in the new April release. Republished the
model to the Premium workspace. Then a connection attempt with ALM toolkit
- fails with Object reference not set to an instance of an object.


FYI this is no longer a road block for me as I've moved forward and removed
the composite model from my development plans. I still have the source PBIX
file to aid in diagnosing this issue.
The file is 988MB in size and does include Incremental refresh on one
table. Happy to supply information where I can to aid in diagnostics.

- David

**Comment by christianwade** [comment]
I think I found it and fixed it. Can you please try the latest version 5.0.20?

**Comment by dgwilson** [comment]
BOOM! Success!
Awesome work.

The Compare succeeds.
Right now both The Service and my local model are the same so no definition
differences to update.

Back in business. Thank you.

**Comment by dgwilson** [comment]
Also... via Edge... I'm getting "AlmTookKitSetup.msi was blocked because it
could harm your device.". ...  I proceed and tell it to keep the file
etc... I have reported it as Safe.

**Comment by christianwade** [comment]
Sounds good! I'll see if anything can be done about the Edge thing. 
Thanks for reporting this!
